name: sia_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  cupertino_icons: ^1.0.8
  url_launcher: ^6.2.6
  file_picker: ^10.3.1
  dio: ^5.4.3
  flutter_quill: ^11.4.1
  super_editor: ^0.3.0-dev.25
  crop_your_image: ^2.0.0
  flutter_box_transform: ^0.4.7
  flutter_resizable_container: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  peanut: ^6.0.0

flutter:
  uses-material-design: true 